builds:
  - binary: compress
    main: ./
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
      - -linkmode=external
    flags:
      - -tags=netgo
    env:
      - CGO_ENABLED=1
      - GO111MODULE=on
    goos:
      - darwin
    goarch:
      - amd64
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}_{{.Arch}}"
  files:
    - README.md
snapshot:
  name_template: "devel"
release:
  disable: true
