# .travis.yml
language: go
# before_install:
# - sudo add-apt-repository ppa:snappy-dev/tools -y
# - sudo apt-get update
# - sudo apt-get install snapcraft rpm -y

# env:
#   needed for the snap pipe:
# - PATH=/snap/bin:$PATH

install:
  # needed for the snap pipe:
  # # - sudo snap install snapcraft --classic
  - go get
  # needed for the docker pipe
services:
  - docker

  # calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
